apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "shopping"
---
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: shopping-analytics-service
  namespace: "shopping"
spec:
  replicas: 1
  image: shopping-analytics-service:1.0.0-SNAPSHOT
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"
      cpu: "1"
  kafka:
    credentialsSecret: shopping-analytics-service-kafka-secret
